class ConfigInit:
    url = 'youurl'
    sendaddr_name = 'youname'
    sendaddr_pswd = 'youpw'
    data_filename = 'login.xls'
    mongo_user = 'name'
    mongo_pw = 'pw'
    mongo_ip = 'ip'
    AccessKey = 'key'
    SecretKey = 'key'
    qiniu_domain = 'domain'
    qiniu_house = 'house'
