class ConfigInit:
    url = 'url'
    sendaddr_name = 'name'
    sendaddr_pswd = 'paswd'
    data_filename = 'login.xls'
    mongo_user = 'root'
    mongo_pw = 'pw'
    mongo_ip = 'ip:27017'
    AccessKey = 'qiniukey'
    SecretKey = 'qiniukey'
    qiniu_domain = 'qiniudomain'
    qiniu_house = 'jimi-imags'