class ConfigInit:
    url = 'url'
    sendaddr_name = 'name'
    sendaddr_pswd = 'pswd'
    data_filename = 'login.xls'
    mongo_user = 'root'
    mongo_pw = 'pw'
    mongo_ip = 'ip:27017'
    AccessKey = 'akey'
    SecretKey = 'skey'
    qiniu_domain = 'domain'
    qiniu_house = 'house'